/** Chambers hidden from the default menu until search or “Show all”. */
export const EXTENDED_MENU_MODES: ReadonlySet<string> = new Set([
  "ward",
  "sanctuary",
  "mimi-rip",
  "private-studio",
  "mimi-drop",
  "memberships",
  "thimble",
  "atelier",
  "house",
  "geo_engine",
  "intel-hub",
  "residue",
  "observatory",
  "mean-median-mode",
  "forecast",
  "brand-intake",
  "codex",
  "brand-voice",
  "architecture",
  "ui-audit",
  "web3-manifest",
  "signals",
  "celestial-calibration",
  "quiet-studio",
  "briefs",
  "loom",
  "thimble",
  "action-board",
  "taste-identity",
  "taste-discovery",
  "latent-constellation",
  "the-lens",
  "obsidian-mirror",
  "nebula",
  "manifesto",
  "checkout-success",
]);

export function isExtendedMenuMode(mode: string): boolean {
  return EXTENDED_MENU_MODES.has(mode);
}

/** Signed-in workflow chambers that benefit from a Studio Map shortcut in chrome. */
export const WORKFLOW_MAP_CHROME_MODES: ReadonlySet<string> = new Set([
  "studio",
  "stand",
  "tailor",
  "signature",
  "scribe",
  "the-edit",
  "the-press",
  "darkroom",
  "pocket",
  "wardrobe",
  "scry",
  "moodboard",
  "briefs",
  "quiet-studio",
  "proscenium",
  "taste-graph",
  "profile",
]);
