export type CanonLayer = "chamber" | "engine" | "artifact" | "infrastructure";

export type CanonModuleStatus = "live" | "aliased" | "stub" | "missing";

export interface CanonModule {
  id: string;
  name: string;
  layer: CanonLayer;
  engine: string;
  priority: number;
  status: CanonModuleStatus;
  canonicalRoute: string;
  implementedMode?: string;
  component?: string;
  aliases: string[];
  inputs: string[];
  generations: string[];
  outputs: string[];
  userFlow: string;
  notes?: string;
}

export const CANON_ROUTE_ALIASES: Record<string, string> = {
  "/": "/studio",
  edit: "the-edit",
  "the-edit": "the-edit",
  press: "the-edit",
  "the-press": "the-press",
  publisher: "the-press",
  pressroom: "the-press",
  export: "the-press",
  "export-chamber": "the-press",
  pocket: "pocket",
  registry: "pocket",
  stand: "stand",
  moodboard: "moodboard",
  "mood-board": "moodboard",
  canvas: "moodboard",
  dossier: "moodboard",
  scribe: "scribe",
  "semantic-portal": "scribe",
  "research-memory": "scribe",
  intelhub: "intel-hub",
  geoengine: "geo_engine",
  geo: "geo_engine",
  "geo-engine": "geo_engine",
  "private-studio": "private-studio",
  "case-study": "private-studio",
  dolls: "mimi-dolls",
  "mimi-dolls": "mimi-dolls",
  "mimi-you": "mimi-dolls",
  rip: "mimi-rip",
  "mimi-rip": "mimi-rip",
  "mimi.rip": "mimi-rip",
  "chamber-map": "chamber-map",
  threads: "scribe",
  "narrative-threads": "scribe",
  "art-style": "tailor",
  scryer: "tailor",
  "style-scryer": "tailor",
  "aesthetic-intelligence": "tailor",
  "style-diagnostics": "tailor",
  atelier: "atelier",
  objects: "atelier",
  "taste-objects": "atelier",
};

export const canonicalizeMimiRoute = (segment: string): string => {
  return CANON_ROUTE_ALIASES[segment] || segment || "studio";
};

export const CANON_MODULES: CanonModule[] = [
  {
    id: "studio",
    name: "Studio / Worktable",
    layer: "chamber",
    engine: "Orchestration Engine",
    priority: 8,
    status: "live",
    canonicalRoute: "/studio",
    implementedMode: "studio",
    component: "InputStudio",
    aliases: ["Worktable"],
    inputs: ["prompt text", "media references", "Tailor logic", "Pocket/Mood Board/Darkroom artifacts", "zine options"],
    generations: ["provider routing", "prompt optimization", "Tailor-aware context synthesis", "asset injection"],
    outputs: ["mini zines", "creative roadmaps", "image prompts", "content briefs", "instruction packets"],
    userFlow: "Start in Studio, combine fragments and references, and receive a structured creative artifact you can save or export.",
  },
  {
    id: "scribe",
    name: "Scribe / Semantic Portal",
    layer: "chamber",
    engine: "Semantic Ingestion Engine",
    priority: 1,
    status: "live",
    canonicalRoute: "/scribe",
    implementedMode: "scribe",
    component: "ScribeChamber",
    aliases: ["Research Memory", "Semantic Portal"],
    inputs: ["raw AI conversations", "chat text", "dialogue paste", "link drops", "highlighted selections"],
    generations: ["signal extraction", "memory atom structuring", "context pack creation"],
    outputs: ["Memory Atoms", "Codex context packs", "documented decisions", "Used Context payloads"],
    userFlow: "Save important conversation fragments and turn them into traceable context Mimi can retrieve later.",
    notes: "Legacy route /research-memory aliases here. ResearchMemory runs inside the Atomize tab.",
  },
  {
    id: "tailor",
    name: "Tailor / Profile Logic",
    layer: "chamber",
    engine: "Preference Synthesis Engine",
    priority: 2,
    status: "live",
    canonicalRoute: "/tailor",
    implementedMode: "tailor",
    component: "TailorHub",
    aliases: ["Profile Logic", "mimi.you calibration"],
    inputs: ["taste declarations", "references", "motifs", "color definitions", "constraints"],
    generations: ["profile synthesis", "semantic constraints", "taste tokenization"],
    outputs: ["Tailor Profile", "Mimi Logic Report", "prompt variables", "identity constraints"],
    userFlow: "Calibrate the taste logic that should guide every future generation.",
  },
  {
    id: "taste-signature",
    name: "Taste Signature",
    layer: "artifact",
    engine: "Signature Report Generator",
    priority: 3,
    status: "live",
    canonicalRoute: "/signature",
    implementedMode: "signature",
    component: "SignatureView",
    aliases: ["Signature Report", "Aesthetic DNA"],
    inputs: ["saved zines", "Tailor profile", "Pocket items", "semantic tokens"],
    generations: ["motif extraction", "lineage synthesis", "signature summary generation"],
    outputs: ["Taste Signature Report", "motif summaries", "aesthetic readings"],
    userFlow: "See the current read of your taste so you can approve or repair Mimi's interpretation.",
  },
  {
    id: "taste-graph",
    name: "Taste Graph / Threads",
    layer: "chamber",
    engine: "Graph-Projection Engine",
    priority: 4,
    status: "live",
    canonicalRoute: "/taste-graph",
    implementedMode: "taste-graph",
    component: "TasteGraph",
    aliases: ["Threads", "Narrative Threads"],
    inputs: ["saved artifacts", "embeddings", "reference tags", "profile data"],
    generations: ["cluster projection", "center-of-gravity calculation", "thread extraction"],
    outputs: ["taste clusters", "narrative threads", "embedding keywords"],
    userFlow: "Inspect how saved references cluster and which taste threads are becoming durable.",
  },
  {
    id: "aesthetic-intelligence",
    name: "Aesthetic Intelligence",
    layer: "chamber",
    engine: "Chromatic Diagnostic Engine",
    priority: 4,
    status: "aliased",
    canonicalRoute: "/aesthetic-intelligence",
    implementedMode: "tailor",
    component: "TailorHub / AestheticIntelligenceChamber",
    aliases: ["Style Diagnostics", "Color Telemetry"],
    inputs: ["saved zines", "palette declarations", "designBrief text"],
    generations: ["dominant tone analysis", "chromatic frequency calculation", "density timelines"],
    outputs: ["style reports", "palette charts", "aesthetic diagnostic insights"],
    userFlow: "Open Tailor Diagnostics to compare your generated portfolio with the active profile and review style drift or chromatic dominance.",
    notes: "Compatibility route opens /tailor/diagnostics. The diagnostic engine remains modular inside Tailor.",
  },
  {
    id: "the-edit",
    name: "The Edit",
    layer: "chamber",
    engine: "Artifact Pipeline Engine",
    priority: 5,
    status: "live",
    canonicalRoute: "/the-edit",
    implementedMode: "the-edit",
    component: "TheEditChamber",
    aliases: ["Press", "Campaign/news surface"],
    inputs: ["Studio outputs", "fragments", "reports", "card decks"],
    generations: ["editorial compilation", "diagnostic framing", "strategy synthesis"],
    outputs: ["strategy reports", "Aesthetic Census", "editorial briefings"],
    userFlow: "Turn scattered material into an editorial read before publishing or exporting it.",
    notes: "Legacy /press aliases here. Distinct from The Press export chamber.",
  },
  {
    id: "the-press",
    name: "The Press / Export Chamber",
    layer: "chamber",
    engine: "Export Manifest Handler",
    priority: 6,
    status: "live",
    canonicalRoute: "/the-press",
    implementedMode: "the-press",
    component: "ThePressChamber / ExportChamber",
    aliases: ["Export Chamber", "Publisher Console"],
    inputs: ["approved artifacts", "manifest JSON", "media", "provenance notes"],
    generations: ["manifest resolution", "export diagnostics", "commerce/web formatting"],
    outputs: ["PDF/DOCX", "share links", "product pages", "Shopify CSV/JSON-LD packs", "portfolio-ready exports", "Keep Tabs RSS (/u/:handle/feed.xml)"],
    userFlow: "Package approved work into a shareable or portfolio-ready artifact. Making a zine public files it in the creator Keep Tabs feed for subscribe-once readers.",
    notes: "Artifact-specific export exists inside AnalysisDisplay via ExportChamber; the canonical top-level route currently opens PublisherDashboard. Public issues also project to RSS via /api/feed?handle=.",
  },
  {
    id: "pocket",
    name: "Pocket / Registry",
    layer: "chamber",
    engine: "Persistence Engine",
    priority: 7,
    status: "live",
    canonicalRoute: "/pocket",
    implementedMode: "pocket",
    component: "Pocket",
    aliases: ["Registry", "Archive"],
    inputs: ["saved media", "links", "zines", "generated assets", "folders"],
    generations: ["local/cloud persistence", "folder mapping", "provenance preservation"],
    outputs: ["persistent archive", "source packs", "reusable context packs"],
    userFlow: "Save and retrieve references without losing source priority or provenance.",
  },
  {
    id: "stand",
    name: "The Stand",
    layer: "chamber",
    engine: "Showcase Engine",
    priority: 7,
    status: "live",
    canonicalRoute: "/stand",
    implementedMode: "stand",
    component: "TheStand",
    aliases: ["Showcase", "Published Works"],
    inputs: ["published zines", "local archive", "community floor"],
    generations: ["cover grid", "issue filtering", "comment threads"],
    outputs: ["personal showcase", "floor feed", "profile seed"],
    userFlow: "Browse your published issues and the community Floor without leaving the Stand.",
  },
  {
    id: "mood-board",
    name: "Mood Board",
    layer: "chamber",
    engine: "Canvas State Engine",
    priority: 11,
    status: "live",
    canonicalRoute: "/moodboard",
    implementedMode: "moodboard",
    component: "MoodBoardChamber",
    aliases: ["Canvas", "Dossier"],
    inputs: ["uploaded images", "links", "board notes", "folders"],
    generations: ["spatial arrangement tracking", "report synthesis", "card deck translation"],
    outputs: ["moodboard reports", "board decks", "Studio prompt context"],
    userFlow: "Arrange references visually and send the board context into Studio.",
    notes: "Legacy /dossier aliases here. DossierView runs inside the chamber shell.",
  },
  {
    id: "intelhub",
    name: "IntelHub",
    layer: "chamber",
    engine: "Grounding Engine",
    priority: 9,
    status: "live",
    canonicalRoute: "/intelhub",
    implementedMode: "intel-hub",
    component: "IntelHub",
    aliases: ["Intel Hub", "Aesthetic Intelligence Hub"],
    inputs: ["links", "brand reports", "Tailor profile", "keywords", "search grounding logic"],
    generations: ["research synthesis", "link parsing", "evidence-vs-inference review", "commerce discovery"],
    outputs: ["approved Used Context", "SEO/editorial briefs", "artifact packs", "Press handoffs", "intelligence audits"],
    userFlow: "Collect evidence, review Tailor inferences, approve Used Context, discover possibilities, and hand a provenance-bearing artifact pack to The Press.",
    notes: "IntelHub orchestrates project state; it does not publish directly. Paired with GeoEngine; canon treats them as related but distinct chambers.",
  },
  {
    id: "geoengine",
    name: "GeoEngine",
    layer: "chamber",
    engine: "Location Context Engine",
    priority: 9,
    status: "live",
    canonicalRoute: "/geoengine",
    implementedMode: "geo_engine",
    component: "TheGEOEngine",
    aliases: ["GEO Engine", "GEO"],
    inputs: ["zine text", "brand reports", "opt-in location/venue parameters", "search grounding logic"],
    generations: ["GEO schema generation", "location-scouting synthesis", "machine-readable brand metadata"],
    outputs: ["GEO manifests / JSON-LD", "location-scouting memos", "AI-readable brand metadata"],
    userFlow: "Turn aesthetic identity into location-aware, search-grounded machine-readable structure.",
  },
  {
    id: "darkroom",
    name: "Darkroom",
    layer: "chamber",
    engine: "Visual Generation Engine",
    priority: 10,
    status: "live",
    canonicalRoute: "/darkroom",
    implementedMode: "darkroom",
    component: "DarkroomView",
    aliases: ["Image Lab"],
    inputs: ["visual prompts", "uploaded references", "Tailor rules", "treatment presets"],
    generations: ["visual analysis", "treatment application", "image generation"],
    outputs: ["generated images", "visual concepts", "reusable anchors"],
    userFlow: "Test visual treatments against references and send strong anchors back into Studio or Pocket.",
  },
  {
    id: "wardrobe",
    name: "Wardrobe",
    layer: "chamber",
    engine: "Catalog & Semantic Storage Engine",
    priority: 12,
    status: "live",
    canonicalRoute: "/wardrobe",
    implementedMode: "wardrobe",
    component: "WardrobeView",
    aliases: ["Closet"],
    inputs: ["garment images", "titles", "categories", "tags", "styling notes"],
    generations: ["metadata embedding", "capsule organization", "Studio handoff context"],
    outputs: ["looks", "capsules", "style references", "generation anchors"],
    userFlow: "Store garments and looks as reusable visual context.",
  },
  {
    id: "thimble",
    name: "Thimble",
    layer: "chamber",
    engine: "Procurement Logic Engine",
    priority: 13,
    status: "live",
    canonicalRoute: "/thimble",
    implementedMode: "thimble",
    component: "ThimbleDashboard",
    aliases: ["Sourcing"],
    inputs: ["Pinterest links", "moodboard reports", "wardrobe gaps", "budget constraints"],
    generations: ["aesthetic tag extraction", "marketplace query mapping", "procurement framing"],
    outputs: ["search terms", "product categories", "sourcing plans"],
    userFlow: "Convert taste signals into concrete sourcing language.",
  },
  {
    id: "sanctuary",
    name: "Sanctuary",
    layer: "chamber",
    engine: "Private Local Store",
    priority: 14,
    status: "live",
    canonicalRoute: "/sanctuary",
    implementedMode: "sanctuary",
    component: "SanctuaryView",
    aliases: ["Local-only vault"],
    inputs: ["sensitive artifacts", "private documents"],
    generations: ["local-only persistence", "privacy boundary enforcement"],
    outputs: ["local-only grounded artifacts"],
    userFlow: "Keep sensitive material usable without sending it through cloud sync.",
  },
  {
    id: "the-ward",
    name: "The Ward / IP Custody",
    layer: "chamber",
    engine: "IP Custody Center",
    priority: 15,
    status: "live",
    canonicalRoute: "/ward",
    implementedMode: "ward",
    component: "TheWard",
    aliases: ["IP Custody Center"],
    inputs: ["metadata notes", "copyright data", "visual artifacts"],
    generations: ["provenance tracking", "specimen records", "custody checks"],
    outputs: ["IP specimen records", "copyright notes", "infringement tracking data"],
    userFlow: "Keep proof and provenance attached to important artifacts.",
  },
  {
    id: "private-studio",
    name: "Private Studio",
    layer: "chamber",
    engine: "Services Chamber",
    priority: 16,
    status: "live",
    canonicalRoute: "/private-studio",
    implementedMode: "private-studio",
    component: "PrivateStudioChamber",
    aliases: ["Services", "Case Study"],
    inputs: ["marketing commentary", "portfolio proof", "generated reports"],
    generations: ["client-facing packaging", "service framing", "proof artifact formatting"],
    outputs: ["service pages", "portfolio packages", "case studies"],
    userFlow: "Turn internal Mimi proof into client-facing work.",
    notes: "Legacy /case-study aliases here.",
  },
  {
    id: "mimi-dolls",
    name: "Mimi Dolls",
    layer: "chamber",
    engine: "Persistent Identity Visualization",
    priority: 17,
    status: "live",
    canonicalRoute: "/mimi-dolls",
    implementedMode: "mimi-dolls",
    component: "MimiDollsChamber",
    aliases: ["Dolls", "mimi.you"],
    inputs: ["Tailor profile", "Research Memory", "moodboards", "generation controls"],
    generations: ["identity consistency tracking", "art-historical reinterpretation", "editorial portrait generation"],
    outputs: ["editorial portraits", "badges", "profile cards", "report covers"],
    userFlow: "Use a stable editorial figure to visualize how your taste evolves across contexts.",
    notes: "Public profile cards remain at /u/:handle. Engine: services/dollEngine (procedural aesthetic + identity pack + masks + companion injection).",
  },
  {
    id: "mimi-rip",
    name: "mimi.rip",
    layer: "chamber",
    engine: "Inverse Taste Projection",
    priority: 17.5,
    status: "live",
    canonicalRoute: "/rip",
    implementedMode: "mimi-rip",
    component: "RipChamber",
    aliases: ["Rip", "Dark Mirror", "Inverse Reading"],
    inputs: ["Taste Graph", "evidence dossier", "likeness antiMotifs", "Doll blind spots", "exclusion principles"],
    generations: ["inverse thesis", "anti-motif map", "opposite palette/silhouette", "shadow experiments"],
    outputs: ["private Rip reading", "optional public mimi.rip card"],
    userFlow: "Read the dark mirror of your graph — refusals, blind spots, and controlled inversions — without replacing your identity on mimi.you.",
    notes: "Private by default. Public skin at mimi.rip/:handle when published. Not diagnosis.",
  },
  {
    id: "art-style",
    name: "Art Style Scryer",
    layer: "chamber",
    engine: "Sovereign Semiotic Scrying Engine",
    priority: 18,
    status: "aliased",
    canonicalRoute: "/art-style",
    implementedMode: "tailor",
    component: "TailorHub / ArtStyleChamber",
    aliases: ["Art Style", "Style Scryer", "Aesthetic Signature Crafter"],
    inputs: ["image uploads", "aesthetic cues", "text snippets"],
    generations: ["pattern extraction", "motif calibration", "style card compositing"],
    outputs: ["Art Style Signature Card", "custom model prompts", "palette configurations"],
    userFlow: "Open Tailor Style Lab, upload references, inspect extracted patterns, and approve reusable style evidence for the active profile.",
    notes: "Compatibility route opens /tailor/style-lab. Style evidence remains linked instead of being embedded into every profile payload."
  },
  {
    id: "atelier",
    name: "Atelier",
    layer: "chamber",
    engine: "Taste Object Archive",
    priority: 19,
    status: "live",
    canonicalRoute: "/atelier",
    implementedMode: "atelier",
    component: "AtelierChamber",
    aliases: ["Objects", "Taste Objects"],
    inputs: ["zine commerce touchpoints", "Shopify-verified product metadata", "semiotic rationale"],
    generations: ["taste-signal persistence", "cross-issue object clustering"],
    outputs: ["pinned taste objects", "desire / buyer-orientation evidence"],
    userFlow: "Pin semiotic commerce objects from a zine as taste signals, then revisit them here across issues. Not a wishlist or cart.",
    notes: "Distinct from the Atelier membership plan. Local-first archive under mimi_atelier_objects::{uid}.",
  }
];

export const CANON_MODULE_BY_ROUTE = CANON_MODULES.reduce<Record<string, CanonModule>>((acc, module) => {
  acc[module.canonicalRoute] = module;
  return acc;
}, {});

export const CANON_MODULE_BY_ID = CANON_MODULES.reduce<Record<string, CanonModule>>((acc, module) => {
  acc[module.id] = module;
  return acc;
}, {});
