export const MIMI_WIDGET_URI = "ui://mimi/studio-v3.html";

export function renderMimiWidgetHtml() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
    :root{color-scheme:light dark;--ink:#17140f;--paper:#f4f0e6;--sheet:#fffdf8;--line:#b8ad9c;--quiet:#71685e;--amber:#b65d2f;font-family:Arial,sans-serif}
    *{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink)}button,textarea{font:inherit}
    .frame{max-width:900px;margin:auto;padding:16px}.chrome{display:flex;justify-content:space-between;gap:20px;align-items:end;border-top:3px solid var(--ink);border-bottom:1px solid var(--ink);padding:12px 0}
    .brand{font:900 clamp(42px,10vw,78px)/.72 Impact,sans-serif;letter-spacing:-.06em;text-transform:uppercase}.brand small{display:block;margin:10px 0 0 4px;font:700 8px/1.2 ui-monospace,monospace;letter-spacing:.23em}
    .issue{text-align:right;font:700 9px/1.5 ui-monospace,monospace;text-transform:uppercase;letter-spacing:.14em}.path{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid var(--ink)}
    .step{padding:10px;border-right:1px solid var(--line);font:700 9px/1.3 ui-monospace,monospace;text-transform:uppercase;letter-spacing:.1em}.step:last-child{border:0}.step.active{background:var(--ink);color:var(--paper)}
    .hero{display:grid;grid-template-columns:1.15fr .85fr;min-height:340px;border-bottom:1px solid var(--ink)}.visual{position:relative;overflow:hidden;background:linear-gradient(135deg,#24201b 0 36%,#baae9e 36% 64%,#8e3d2c 64%)}
    .visual:after{content:"";position:absolute;width:42%;height:85%;right:8%;top:8%;border:18px solid rgba(255,250,240,.55);transform:rotate(8deg)}.headline{position:absolute;z-index:2;left:18px;right:18px;bottom:18px;color:#fff8e9;font:400 clamp(35px,7vw,62px)/.84 Georgia,serif;letter-spacing:-.05em}
    .panel{padding:22px;background:var(--sheet);display:flex;flex-direction:column;justify-content:space-between}.kicker{color:var(--amber);font:700 9px/1 ui-monospace,monospace;letter-spacing:.18em;text-transform:uppercase}
    h1,h2,p{margin-top:0}h2{font:400 31px/.98 Georgia,serif}.panel p,.brief p{color:var(--quiet);font-size:12px;line-height:1.55}textarea{width:100%;min-height:88px;padding:11px;border:1px solid var(--line);background:transparent;color:inherit;resize:vertical}
    .actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}button,.link{appearance:none;border:1px solid var(--ink);background:transparent;color:inherit;padding:10px 12px;cursor:pointer;font:700 9px/1 ui-monospace,monospace;text-transform:uppercase;letter-spacing:.1em;text-decoration:none}.primary{background:var(--ink);color:var(--paper)}
    .brief{display:grid;grid-template-columns:.72fr 1.28fr;border-bottom:1px solid var(--ink)}.brief-side{padding:22px;background:var(--ink);color:var(--paper)}.brief-side p{color:#cfc5b7}.brief-main{padding:22px;background:var(--sheet)}
    .field{padding:12px 0;border-top:1px solid var(--line)}.field b{display:block;margin-bottom:6px;font:700 8px/1 ui-monospace,monospace;text-transform:uppercase;letter-spacing:.14em;color:var(--amber)}.field span{font:400 18px/1.25 Georgia,serif}
    .tailor{display:grid;grid-template-columns:.8fr 1.2fr;border-bottom:1px solid var(--ink)}.tailor-summary{padding:22px;background:var(--ink);color:var(--paper)}.tailor-summary p{color:#cfc5b7}.tailor-main{padding:22px;background:var(--sheet)}
    .confidence{font:400 48px/.9 Georgia,serif;letter-spacing:-.06em}.chips{display:flex;flex-wrap:wrap;gap:6px}.chip{border:1px solid var(--line);padding:6px 8px;font:700 8px/1.2 ui-monospace,monospace;text-transform:uppercase;letter-spacing:.08em}
    .rule-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.rule-list{margin:0;padding-left:18px;color:var(--quiet);font-size:11px;line-height:1.5}.question{margin-top:18px;padding:14px;border:1px solid var(--amber);background:color-mix(in srgb,var(--amber) 8%,transparent)}
    .footer{display:flex;justify-content:space-between;gap:16px;padding:12px 0;color:var(--quiet);font:700 8px/1.4 ui-monospace,monospace;text-transform:uppercase;letter-spacing:.12em}
    @media(max-width:640px){.hero,.brief,.tailor{grid-template-columns:1fr}.rule-grid{grid-template-columns:1fr}.visual{min-height:280px}.path{grid-template-columns:repeat(2,1fr)}.step:nth-child(2){border-right:0}.chrome{align-items:start}.issue{font-size:7px}}
    @media(prefers-color-scheme:dark){:root{--ink:#f4f0e6;--paper:#17140f;--sheet:#211d18;--line:#5d5449;--quiet:#b8ad9c;--amber:#ef9a68}.visual{background:linear-gradient(135deg,#0e0d0b 0 36%,#74695d 36% 64%,#873b2d 64%)}}
  </style>
</head>
<body>
  <main id="root"></main>
  <script>
    (function(){
      var root=document.getElementById('root'),rpcId=0,pending=new Map(),bridgeReady=false;
      function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
      function request(method,params){return new Promise(function(resolve,reject){var id=++rpcId;pending.set(id,{resolve:resolve,reject:reject});window.parent.postMessage({jsonrpc:'2.0',id:id,method:method,params:params},'*')})}
      function notify(method,params){window.parent.postMessage({jsonrpc:'2.0',method:method,params:params},'*')}
      function chrome(title){return '<div class="chrome"><div class="brand">Mimi<small>Creative intelligence, visibly sourced</small></div><div class="issue">ChatGPT edition<br>'+esc(title||'Untitled issue')+'</div></div>'}
      function path(active){return '<nav class="path">'+['Collect','Shape','Create','Publish'].map(function(label,i){return '<div class="step '+(i===active?'active':'')+'">0'+(i+1)+' / '+label+'</div>'}).join('')+'</nav>'}
      function frame(body){root.innerHTML='<div class="frame">'+body+'<footer class="footer"><span>User as final editor</span><span>Used Context stays visible</span></footer></div>'}
      function studio(data){
        data=data||{};frame(chrome(data.projectTitle)+path(0)+'<section class="hero"><div class="visual"><div class="headline">Turn source material into an editorial issue.</div></div><div class="panel"><div><p class="kicker">01 / Source material</p><h2>What are you trying to make sense of?</h2><p>Start with a fragment, reference, tension, or unfinished idea. Mimi will help you shape it before anything becomes final.</p><textarea id="source" placeholder="Paste a fragment, question, or creative direction..."></textarea></div><div class="actions"><button id="shape" class="primary">Shape the brief</button><a class="link" href="http://localhost:3000" target="_blank">Open full studio</a></div></div></section>');
        document.getElementById('shape').onclick=async function(){var value=document.getElementById('source').value.trim();if(!value)return;try{var result=bridgeReady?await request('tools/call',{name:'shape_mimi_brief',arguments:{sourceMaterial:value}}):window.openai&&window.openai.callTool?await window.openai.callTool('shape_mimi_brief',{sourceMaterial:value}):null;update(result&&result.structuredContent?result.structuredContent:result&&result.result&&result.result.structuredContent?result.result.structuredContent:result)}catch(error){document.getElementById('shape').textContent='Continue in ChatGPT'}}
      }
      function brief(data){frame(chrome(data.title)+path(1)+'<section class="brief"><aside class="brief-side"><p class="kicker">Shaped, not final</p><h2>'+esc(data.title)+'</h2><p>'+esc(data.summary)+'</p><p>The brief is a proposal. Keep, edit, or reject any part before developing the issue.</p></aside><div class="brief-main">'+[['Editorial intention',data.editorialIntention],['Central tension',data.centralTension],['Desired feeling',data.desiredFeeling],['Avoid',data.avoid],['Output',data.outputWanted]].map(function(item){return '<div class="field"><b>'+esc(item[0])+'</b><span>'+esc(item[1]||'Open for your direction')+'</span></div>'}).join('')+'<div class="actions"><button id="revise">Revise in chat</button><a class="link primary" href="http://localhost:3000" target="_blank">Develop in Studio</a></div></div></section>');document.getElementById('revise').onclick=function(){var prompt='Revise this Mimi brief while preserving my source material and showing what changed.';if(bridgeReady)notify('ui/message',{role:'user',content:[{type:'text',text:prompt}]});else if(window.openai&&window.openai.sendFollowUpMessage)window.openai.sendFollowUpMessage({prompt:prompt})}}
      function flow(data){frame(chrome('How Mimi works')+path(-1)+'<section class="brief"><aside class="brief-side"><p class="kicker">The creator journey</p><h2>Evidence before output.</h2><p>Mimi preserves your authority by making every transition visible.</p></aside><div class="brief-main">'+(data.steps||[]).map(function(step,i){return '<div class="field"><b>0'+(i+1)+' / '+esc(step.title)+'</b><span>'+esc(step.description)+'</span></div>'}).join('')+'</div></section>')}
      function sendPrompt(prompt){if(bridgeReady)notify('ui/message',{role:'user',content:[{type:'text',text:prompt}]});else if(window.openai&&window.openai.sendFollowUpMessage)window.openai.sendFollowUpMessage({prompt:prompt})}
      function tailor(data){var item=data.widget||{},ref=data.profileRef||{},pct=Math.round((item.confidence||0)*100),rules=function(values){return (values||[]).map(function(value){return '<li>'+esc(value)+'</li>'}).join('')||'<li>Open for evidence</li>'};frame(chrome(item.headline||'Tailor review')+path(1)+'<section class="tailor"><aside class="tailor-summary"><p class="kicker">Evidence-linked interpretation</p><h2>'+esc(item.headline||'Tailor review')+'</h2><div class="confidence">'+pct+'%</div><p>Overall confidence · '+esc(item.state||'needs review')+'</p><div class="chips">'+(item.signals||[]).map(function(value){return '<span class="chip">'+esc(value)+'</span>'}).join('')+'</div><p style="margin-top:18px">Profile '+esc(ref.profileId||'')+' · schema '+esc(ref.schemaVersion||'')+'</p></aside><div class="tailor-main"><p class="kicker">Working thesis</p><h2>'+esc(item.thesis||'No thesis yet')+'</h2><div class="rule-grid"><div class="field"><b>Preserve</b><ul class="rule-list">'+rules(item.preserve)+'</ul></div><div class="field"><b>Avoid</b><ul class="rule-list">'+rules(item.avoid)+'</ul></div></div>'+(item.nextQuestion?'<div class="question"><p class="kicker">Highest-value next question</p><h2>'+esc(item.nextQuestion.prompt)+'</h2><p>'+esc(item.nextQuestion.reason)+'</p></div>':'')+'<div class="actions"><button id="confirm-tailor" class="primary">Confirm thesis</button><button id="correct-tailor">Correct Mimi</button><button id="import-tailor">Import evidence</button></div></div></section>');document.getElementById('confirm-tailor').onclick=function(){sendPrompt('Confirm this Tailor thesis as my approved direction. Keep the evidence and provenance attached, and do not change the profile silently.')};document.getElementById('correct-tailor').onclick=function(){sendPrompt('I want to correct this Tailor profile. Ask me what the thesis gets wrong, then show the proposed change before applying it.')};document.getElementById('import-tailor').onclick=function(){sendPrompt('Help me import additional Tailor evidence. Keep supplied evidence separate from Mimi inferences and show what changes.')}}
      function update(data){if(!data)return;if(data.structuredContent)data=data.structuredContent;if(data.result&&data.result.structuredContent)data=data.result.structuredContent;if(data.kind==='brief')brief(data);else if(data.kind==='core_flow')flow(data);else if(data.kind==='tailor_review')tailor(data);else studio(data)}
      window.addEventListener('message',function(event){if(event.source!==window.parent)return;var message=event.data;if(!message||message.jsonrpc!=='2.0')return;if(message.id&&pending.has(message.id)){var item=pending.get(message.id);pending.delete(message.id);message.error?item.reject(message.error):item.resolve(message.result);return}if(message.method==='ui/notifications/tool-result')update(message.params&&message.params.structuredContent||message.params)});
      async function connect(){try{await request('ui/initialize',{appInfo:{name:'Mimi Studio',version:'3.0.0'},appCapabilities:{tools:{}},protocolVersion:'2025-11-21'});bridgeReady=true;notify('ui/notifications/initialized',{})}catch(error){bridgeReady=false}if(window.openai&&window.openai.toolOutput)update(window.openai.toolOutput)}
      studio({projectTitle:'Untitled issue'});if(window.parent!==window||window.openai)connect();
    })();
  </script>
</body>
</html>`;
}
