/**
 * Sync Cursor Cloud Agent injected secrets into `.env.local` for Mimi dev.
 *
 * Cursor exposes dashboard secrets as process env vars at agent runtime; the
 * Express + Vite dev server also reads `.env.local` (see `server.ts`). This
 * bridge keeps both paths aligned without committing credentials.
 *
 * Run: npm run sync:cloud-env
 * Idempotent — safe in `.cursor/environment.json` install scripts.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const ENV_LOCAL = path.join(ROOT, ".env.local");

/** Canonical runtime keys Mimi reads (subset of `.env.example`). */
const SYNC_KEYS = [
  "AI_GATEWAY_API_KEY",
  "VERCEL_OIDC_TOKEN",
  "GEMINI_API_KEY",
  "API_KEY",
  "OPENAI_API_KEY",
  "ANTHROPIC_API_KEY",
  "OPENROUTER_API_KEY",
  "REPLICATE_API_TOKEN",
  "REPLICATE_API_KEY",
  "CURSOR_API_KEY",
  "APIFY_TOKEN",
  "DATABASE_URL",
  "NEON_DATABASE_URL",
  "NEON_POOLED_DATABASE_URL",
  "FIREBASE_SERVICE_ACCOUNT",
  "FIREBASE_SERVICE_ACCOUNT_FILE",
  "FIREBASE_FIRESTORE_DATABASE_ID",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
  "FIREBASE_MEASUREMENT_ID",
  "STRIPE_SECRET_KEY",
  "STRIPE_WEBHOOK_SECRET",
  "PINTEREST_ACCESS_TOKEN",
] as const;

/** When the canonical name is unset, try these aliases (Cursor secret naming). */
const ALIASES: Partial<Record<(typeof SYNC_KEYS)[number], string[]>> = {
  AI_GATEWAY_API_KEY: ["AI_GATEWAY_KEY"],
};

const parseEnvFile = (content: string): Map<string, string> => {
  const map = new Map<string, string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1);
    map.set(key, value);
  }
  return map;
};

const serializeEnv = (map: Map<string, string>): string => {
  const lines = [
    "# Generated by scripts/syncCloudAgentEnv.ts — do not commit.",
    `# Synced: ${new Date().toISOString()}`,
    "",
  ];
  for (const key of SYNC_KEYS) {
    const value = map.get(key);
    if (value) lines.push(`${key}=${value}`);
  }
  for (const [key, value] of map) {
    if (!(SYNC_KEYS as readonly string[]).includes(key) && value) {
      lines.push(`${key}=${value}`);
    }
  }
  lines.push("");
  return lines.join("\n");
};

const resolveFromProcess = (key: (typeof SYNC_KEYS)[number]): string | undefined => {
  const direct = process.env[key]?.trim();
  if (direct) return direct;
  for (const alias of ALIASES[key] ?? []) {
    const aliased = process.env[alias]?.trim();
    if (aliased) return aliased;
  }
  return undefined;
};

const main = () => {
  const existing = fs.existsSync(ENV_LOCAL)
    ? parseEnvFile(fs.readFileSync(ENV_LOCAL, "utf8"))
    : new Map<string, string>();

  let updated = 0;
  for (const key of SYNC_KEYS) {
    const fromCloud = resolveFromProcess(key);
    if (!fromCloud) continue;
    if (existing.get(key) !== fromCloud) {
      existing.set(key, fromCloud);
      updated += 1;
    }
  }

  const hasAnySyncedKey = SYNC_KEYS.some((key) => Boolean(existing.get(key)));
  if (!hasAnySyncedKey) {
    console.log("sync:cloud-env: no cloud secrets found; skipping .env.local");
    return;
  }

  if (updated === 0 && fs.existsSync(ENV_LOCAL)) {
    console.log("sync:cloud-env: .env.local already up to date");
    return;
  }

  fs.writeFileSync(ENV_LOCAL, serializeEnv(existing), "utf8");
  console.log(`sync:cloud-env: wrote ${updated} updated key(s) to .env.local`);
};

main();
